name: megatronix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  http: ^1.3.0
  lottie: ^3.3.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_secure_storage: ^9.2.4
  animated_text_kit: ^4.2.3
  onesignal_flutter: ^5.3.0
  toastification: ^3.0.2
  image_picker: ^1.1.2
  hugeicons: ^0.0.10
  url_launcher: ^6.3.1
  animate_do: ^4.2.0
  blinking_text: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  easy_image_viewer: ^1.5.1
  intl: ^0.20.2
  video_player: ^2.9.5
  chewie: ^1.11.3
  simple_speed_dial: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/megatronix.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/socials/
    - assets/videos/

  fonts:
    - family: DaggerSquare
      fonts:
        - asset: assets/fonts/DaggerSquare.otf
    - family: Couture
      fonts:
        - asset: assets/fonts/Couture.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
